# Generated by Django 2.2.16 on 2022-02-24 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='support', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
