# Generated by Django 2.2.16 on 2022-02-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='supporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Support'),
        ),
    ]
