# Generated by Django 2.2.16 on 2022-02-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20220224_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='supporter',
        ),
    ]
