# Generated by Django 2.2.16 on 2022-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20220224_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
