# Generated by Django 2.2.16 on 2022-02-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_support_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='counter',
        ),
    ]
