# Generated by Django 2.2.16 on 2022-02-25 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_support_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='support', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
