# Generated by Django 2.2.16 on 2022-02-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tickets.Ticket'),
        ),
    ]
